project_id = "iuzmjhndaapftnxasdyc"

[functions.listing-share-image]
verify_jwt = false

[functions.notify-new-message]
verify_jwt = true

[functions.notify-request-update]
verify_jwt = true

[functions.notify-friend-request]
verify_jwt = true

[functions.calculate-balances]
verify_jwt = true

[functions.notify-expense-added]
verify_jwt = false

[functions.create-stripe-session]
verify_jwt = true

[functions.create-stripe-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
